// Code generated by protoc-gen-go. DO NOT EDIT.
// source: item.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Item struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Item) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Item) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ShowItemDetailRequest struct {
	ItemId               int64    `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowItemDetailRequest) Reset()         { *m = ShowItemDetailRequest{} }
func (m *ShowItemDetailRequest) String() string { return proto.CompactTextString(m) }
func (*ShowItemDetailRequest) ProtoMessage()    {}
func (*ShowItemDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{1}
}

func (m *ShowItemDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowItemDetailRequest.Unmarshal(m, b)
}
func (m *ShowItemDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowItemDetailRequest.Marshal(b, m, deterministic)
}
func (m *ShowItemDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowItemDetailRequest.Merge(m, src)
}
func (m *ShowItemDetailRequest) XXX_Size() int {
	return xxx_messageInfo_ShowItemDetailRequest.Size(m)
}
func (m *ShowItemDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowItemDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShowItemDetailRequest proto.InternalMessageInfo

func (m *ShowItemDetailRequest) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

type ShowItemDetailResponse struct {
	Data                 *Item    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowItemDetailResponse) Reset()         { *m = ShowItemDetailResponse{} }
func (m *ShowItemDetailResponse) String() string { return proto.CompactTextString(m) }
func (*ShowItemDetailResponse) ProtoMessage()    {}
func (*ShowItemDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{2}
}

func (m *ShowItemDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowItemDetailResponse.Unmarshal(m, b)
}
func (m *ShowItemDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowItemDetailResponse.Marshal(b, m, deterministic)
}
func (m *ShowItemDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowItemDetailResponse.Merge(m, src)
}
func (m *ShowItemDetailResponse) XXX_Size() int {
	return xxx_messageInfo_ShowItemDetailResponse.Size(m)
}
func (m *ShowItemDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowItemDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShowItemDetailResponse proto.InternalMessageInfo

func (m *ShowItemDetailResponse) GetData() *Item {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ShowItemDetailResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Item)(nil), "pb.Item")
	proto.RegisterType((*ShowItemDetailRequest)(nil), "pb.ShowItemDetailRequest")
	proto.RegisterType((*ShowItemDetailResponse)(nil), "pb.ShowItemDetailResponse")
}

func init() { proto.RegisterFile("item.proto", fileDescriptor_6007f868cf6553df) }

var fileDescriptor_6007f868cf6553df = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0xa5, 0xd9, 0x2f, 0x9d, 0x85, 0x3d, 0x0c, 0x7e, 0xc4, 0xc5, 0x43, 0xe9, 0x69, 0x4f, 0x45,
	0xd6, 0xbf, 0x50, 0x90, 0x5c, 0x64, 0x89, 0x3f, 0x40, 0x52, 0x33, 0x68, 0x60, 0xbb, 0x89, 0xcd,
	0x88, 0x7f, 0x5f, 0x92, 0x5a, 0xd0, 0xa5, 0xc7, 0xf7, 0x31, 0xef, 0x3d, 0x06, 0xc0, 0x31, 0x75,
	0x75, 0xe8, 0x3d, 0x7b, 0x14, 0xa1, 0xad, 0x9e, 0x61, 0xae, 0x98, 0x3a, 0xdc, 0x80, 0x50, 0x8d,
	0x2c, 0xca, 0x62, 0x37, 0xd3, 0x42, 0x35, 0x78, 0x05, 0x0b, 0x76, 0x7c, 0x24, 0x29, 0xca, 0x62,
	0x77, 0xa9, 0x07, 0x80, 0x25, 0xac, 0x2d, 0xc5, 0xb7, 0xde, 0x05, 0x76, 0xfe, 0x24, 0x67, 0x59,
	0xfb, 0x4b, 0x55, 0x0f, 0x70, 0xfd, 0xf2, 0xe1, 0xbf, 0x53, 0x66, 0x43, 0x6c, 0xdc, 0x51, 0xd3,
	0xe7, 0x17, 0x45, 0xc6, 0x5b, 0x58, 0xa5, 0xea, 0x57, 0x67, 0x7f, 0x5b, 0x96, 0x09, 0x2a, 0x5b,
	0x1d, 0xe0, 0xe6, 0xfc, 0x22, 0x06, 0x7f, 0x8a, 0x84, 0xf7, 0x30, 0xb7, 0x86, 0x4d, 0xf6, 0xaf,
	0xf7, 0x17, 0x75, 0x68, 0xeb, 0xe4, 0xd2, 0x99, 0x45, 0x09, 0xab, 0x8e, 0x62, 0x34, 0xef, 0xe3,
	0xc6, 0x11, 0xee, 0x0f, 0xb0, 0x48, 0xbe, 0x88, 0x4f, 0xb0, 0xf9, 0x1f, 0x8d, 0x77, 0x29, 0x64,
	0x72, 0xe0, 0x76, 0x3b, 0x25, 0x0d, 0x4b, 0xda, 0x65, 0x7e, 0xd8, 0xe3, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x43, 0xb0, 0x7f, 0x9c, 0x3e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ItemsClient is the client API for Items service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ItemsClient interface {
	ShowItemDetail(ctx context.Context, in *ShowItemDetailRequest, opts ...grpc.CallOption) (*ShowItemDetailResponse, error)
}

type itemsClient struct {
	cc *grpc.ClientConn
}

func NewItemsClient(cc *grpc.ClientConn) ItemsClient {
	return &itemsClient{cc}
}

func (c *itemsClient) ShowItemDetail(ctx context.Context, in *ShowItemDetailRequest, opts ...grpc.CallOption) (*ShowItemDetailResponse, error) {
	out := new(ShowItemDetailResponse)
	err := c.cc.Invoke(ctx, "/pb.Items/ShowItemDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemsServer is the server API for Items service.
type ItemsServer interface {
	ShowItemDetail(context.Context, *ShowItemDetailRequest) (*ShowItemDetailResponse, error)
}

// UnimplementedItemsServer can be embedded to have forward compatible implementations.
type UnimplementedItemsServer struct {
}

func (*UnimplementedItemsServer) ShowItemDetail(ctx context.Context, req *ShowItemDetailRequest) (*ShowItemDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowItemDetail not implemented")
}

func RegisterItemsServer(s *grpc.Server, srv ItemsServer) {
	s.RegisterService(&_Items_serviceDesc, srv)
}

func _Items_ShowItemDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowItemDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServer).ShowItemDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Items/ShowItemDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServer).ShowItemDetail(ctx, req.(*ShowItemDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Items_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Items",
	HandlerType: (*ItemsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShowItemDetail",
			Handler:    _Items_ShowItemDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "item.proto",
}
